dist:     trusty
sudo:     required
language: cpp

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

env:
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Release

matrix:
    exclude:
        - os: osx
          env: TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
        - os: osx
          env: TARGET_CPU=x86 BUILD_CONFIGURATION=Release

before_install:
    - source install-$TRAVIS_OS_NAME.sh
    - git clone http://github.com/llvm-mirror/llvm --branch release_34

script:
    - LLVM_VERSION=3.4.2
    - THIS_DIR=`pwd`

    - source set-env-vars.sh

    - mkdir $LLVM_RELEASE_NAME
    - mkdir llvm/build
    - cd llvm/build

    - cmake .. -DCMAKE_INSTALL_PREFIX=$THIS_DIR/$LLVM_RELEASE_DIR -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DHAVE_SANITIZER_MSAN_INTERFACE_H=0 -DLLVM_BUILD_32_BITS=$LLVM_BUILD_32_BITS -DLLVM_TARGETS_TO_BUILD=X86 -DLLVM_ENABLE_TERMINFO=OFF -DLLVM_ENABLE_ZLIB=OFF -DLLVM_INCLUDE_DOCS=OFF -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_INCLUDE_TESTS=OFF -DLLVM_INCLUDE_TOOLS=OFF

    - make
    - make install

    - cd $THIS_DIR
    - tar -cJf $LLVM_RELEASE_FILE $LLVM_RELEASE_DIR

    - ls

before_deploy:
    - source set-env-vars.sh

    - echo "Deploying $LLVM_RELEASE_FILE to GitHub releases..."

deploy:
    provider: releases
    api_key:
        secure: lBqOSkQjhEn91Vkk0IWYEOgeiixph+lC1cnu+ng5ZIcxYD/FRSmv60qrB8hG/rex4O1LSAvJYx0WP2dIJymI5QmUZqwK2nB2m24b1vytvcgmY5oFbxHWUdV/ZgIakkhJqXoMEcVSUUoukpdfOwgnsCMClAoHqhghbLqFj8nz6FAyu8Q/JKzLR7d99Nuj6TSjLPazNjhamcOn6nKQEPW5Ut2Au8n+cGlL6IQWq477Q5uXFK0VL6gZP+TuEVpgf628RBmnDiHyrrnTL9SEw279/GES91h5P/S+MSBw5pD6oOzc5TIeDwb0j+UwAnJSQm/K9fHxWXK2+G6sVJ90zOs2vE27l7oqfzjUcIzy+Zo2bO6U9+77vHklGIU+JlW5tMLH1vG0HQg9YN8cL1amdFJDxh/rDOhs8pqj5nMLFAZ5jwcZsG3UPFBOs4cP8daGYi6EqCpbIFRfZ0thpPiLUEjvwe0FqLiuh+FWp2q5+5JP+WvyRyWrE3krnakmYGbBknMbq1yyIKjwEU42sktAIMkvRzfQs4OiijCv5ZaA7oDK6oSPUhlRkmvZytqIqICubRRRsj76QPAUpXCdTgg1VvGJp+EELX1WBZhRrrKWezu+bTRBLBAIy44RFTHnt+bC9XjEWLtzZFVupsoXHgGmnfI3iiSAvQccJaSz5FAcn/krmUc=

    file: $LLVM_RELEASE_FILE

#    on:
#        tags: true
